# Generated by Django 2.2.4 on 2019-08-20 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField()),
                ('lname', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('dateCreated', models.DateTimeField()),
                ('accountNumber', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionAccessRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionAccess', models.TextField()),
                ('transactionAccessDesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTypeRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionType', models.TextField()),
                ('transactionDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('personId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bankApp.Person')),
            ],
        ),
        migrations.CreateModel(
            name='BankApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastTransactionDate', models.DateTimeField()),
                ('transactionDescription', models.CharField(max_length=150)),
                ('balance', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('transactionAccess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankApp.TransactionAccessRef')),
                ('transactionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankApp.TransactionTypeRef')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankApp.Credentials')),
            ],
        ),
    ]
